// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQabzLTL6kZhMEcR3W81VeVaYGuJycfI',
    appId: '1:238605389958:web:40ed75e6f4f42b208a4107',
    messagingSenderId: '238605389958',
    projectId: 'aksiseru-3a49f',
    authDomain: 'aksiseru-3a49f.firebaseapp.com',
    storageBucket: 'aksiseru-3a49f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAneFof1umKTrOM9Tacb2ET0Zxcfm_A4DY',
    appId: '1:238605389958:android:2c283c678311a6b38a4107',
    messagingSenderId: '238605389958',
    projectId: 'aksiseru-3a49f',
    storageBucket: 'aksiseru-3a49f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcf6cfCBpetBOPPFHYdYiFpg13tEdM9aw',
    appId: '1:238605389958:ios:2cbd3063565fec8c8a4107',
    messagingSenderId: '238605389958',
    projectId: 'aksiseru-3a49f',
    storageBucket: 'aksiseru-3a49f.appspot.com',
    iosBundleId: 'com.example.aksiSeruApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcf6cfCBpetBOPPFHYdYiFpg13tEdM9aw',
    appId: '1:238605389958:ios:2cbd3063565fec8c8a4107',
    messagingSenderId: '238605389958',
    projectId: 'aksiseru-3a49f',
    storageBucket: 'aksiseru-3a49f.appspot.com',
    iosBundleId: 'com.example.aksiSeruApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAQabzLTL6kZhMEcR3W81VeVaYGuJycfI',
    appId: '1:238605389958:web:35e6773c3fe5cb268a4107',
    messagingSenderId: '238605389958',
    projectId: 'aksiseru-3a49f',
    authDomain: 'aksiseru-3a49f.firebaseapp.com',
    storageBucket: 'aksiseru-3a49f.appspot.com',
  );
}
